dot_R0R1R1_rel_opts – ForDot
dot_R0R1R1_rel_opts Function
Seyed Ali Ghasemi
BSD 3-Clause
17 statements
Source File
private pure function dot_R0R1R1_rel_opts(u, v, option) result(a)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), dimension(:), contiguous :: u
real(kind=rk), intent(in), dimension(:), contiguous :: v
character(len=*), intent(in) :: option
Return Value real(kind=rk)
Calls
Called by
Source Code
   pure function dot_R0R1R1_rel_opts(u,v, option) result(a)
      real(rk), dimension(:), intent(in), contiguous  :: u, v
      character(*),           intent(in)              :: option
      real(rk)                                        :: a
      select case (option)
       case ('m1')
         a = dot_product(u,v)
       case ('m2')
         a = md_2(u,v)
      case ('m3')
         a = md_3(u,v)
      case ('m4')
         a = md_4(u,v)
       case default
         a = dot_product(u,v)
      end select
   end function dot_R0R1R1_rel_opts
Call graph
dot_r0r1r1_rel_opts calls md_2, md_3, md_4
md_2 calls dot
dot_opts calls dot_r0r1r1_rel_opts
dot_r0r1r1_rel calls dot_opts
dot_product calls dot_r0r1r1_rel
test_dot1 calls dot_product
test_dot2 calls dot_product