dot_R0R1R1_rel – ForDot
dot_R0R1R1_rel Function
Seyed Ali Ghasemi
28 statements
Source File
private impure function dot_R0R1R1_rel(u, v, method, option) result(a)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: u(:)
real(kind=rk), intent(in), contiguous :: v(:)
character(len=*), intent(in) :: method
character(len=*), intent(in) :: option
Return Value real(kind=rk)
Calls
Called by
Source Code
   impure function dot_R0R1R1_rel(u,v,method,option) result(a)
#else
   pure function dot_R0R1R1_rel(u,v,method,option) result(a)
#endif
      real(rk),     intent(in), contiguous :: u(:)
      real(rk),     intent(in), contiguous :: v(:)
      character(*), intent(in)             :: method
      character(*), intent(in)             :: option
      real(rk)                             :: a
      select case (method)
#if defined(USE_COARRAY)
       case ('coarray')
         block
            integer               :: i, im, nimg, m
            integer               :: block_size(num_images()), start_elem(num_images()), end_elem(num_images())
            real(rk), allocatable :: a_block[:], u_block(:)[:], v_block(:)[:]
            im   = this_image()
            nimg = num_images()
            m    = size(u)
            call compute_block_ranges(size(u), nimg, block_size, start_elem, end_elem)
            allocate(u_block(block_size(im))[*], v_block(block_size(im))[*], a_block[*])
            u_block(:)[im] = u(start_elem(im):end_elem(im))
            v_block(:)[im] = v(start_elem(im):end_elem(im))
            a_block[im] = dot_opts(u_block(:)[im],v_block(:)[im],option)
            call co_sum(a_block, result_image=1)
            a = a_block[1]
            ! sync all
            ! if (im == 1) then
            !    a = 0.0_rk
            !    do i = 1, nimg
            !       a = a + a_block[i]
            !    end do
            ! end if
         end block
#endif
       case ('default')
         a = dot_opts(u, v, option)
      end select
   end function dot_R0R1R1_rel
Call graph
dot_r0r1r1_rel calls block_size, end_elem, dot_opts, compute_block_ranges, start_elem, u_block, v_block
dot_opts calls dot_r0r1r1_rel_opts
dot_r0r1r1_rel_opts calls md_2, md_3, md_4
md_2 calls dot
dot_product calls dot_r0r1r1_rel