dot_R0R1R1_rel_coarray – ForDot
dot_R0R1R1_rel_coarray Function
Seyed Ali Ghasemi
26 statements
Source File
private impure function dot_R0R1R1_rel_coarray(u, v, option, coarray) result(a)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: u(:)
real(kind=rk), intent(in) :: v(:)
character(len=*), intent(in) :: option
logical, intent(in) :: coarray
Return Value real(kind=rk)
Calls
Called by
Source Code
   impure function dot_R0R1R1_rel_coarray(u,v,option,coarray) result(a)
      real(rk),     intent(in) :: u(:)
      real(rk),     intent(in) :: v(:)
      character(*), intent(in)             :: option
      real(rk)                             :: a
      logical,      intent(in)             :: coarray
#if defined(USE_COARRAY)
      integer               :: i, im, nimg, m
      integer               :: block_size(num_images()), start_elem(num_images()), end_elem(num_images())
      real(rk), allocatable :: a_block[:], u_block(:)[:], v_block(:)[:]
      im   = this_image()
      nimg = num_images()
      m    = size(u)
      call compute_block_ranges(size(u), nimg, block_size, start_elem, end_elem)
      allocate(u_block(block_size(im))[*], v_block(block_size(im))[*], a_block[*])
      u_block(:)[im] = u(start_elem(im):end_elem(im))
      v_block(:)[im] = v(start_elem(im):end_elem(im))
      a_block[im] = dot_opts(u_block(:)[im],v_block(:)[im],option)
      ! call co_sum(a_block, result_image=1)
      ! a = a_block[1]
      sync all
      if (im == 1) then
         a = 0.0_rk
         do i = 1, nimg
            a = a + a_block[i]
         end do
      end if
#else
      a = dot_product(u, v, option)
#endif
   end function dot_R0R1R1_rel_coarray
Call graph
dot_r0r1r1_rel_coarray calls dot_opts, compute_block_ranges
dot_opts calls dot_r0r1r1_rel_opts
dot_r0r1r1_rel_opts calls md_2, md_3, md_4
md_2 calls dot
dot_product calls dot_r0r1r1_rel_coarray