md_2 – ForDot
md_2 Function
Seyed Ali Ghasemi
6 statements
Source File
private pure function md_2(u, v) result(a)
Uses
external_interfaces_dot
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), dimension(:), contiguous :: u
real(kind=rk), intent(in), dimension(:), contiguous :: v
Return Value real(kind=rk)
Calls
Called by
Source Code
   pure function md_2(u,v) result(a)
      use external_interfaces_dot
      real(rk), dimension(:), intent(in), contiguous :: u, v
      real(rk)                                       :: a
      a = dot(size(u),u,1,v,1)
   end function md_2
Call graph
md_2 calls dot
dot_r0r1r1_rel_opts calls md_2
dot_opts calls dot_r0r1r1_rel_opts
dot_r0r1r1_rel calls dot_opts
dot_r0r1r1_rel_coarray calls dot_opts
dot_product calls dot_r0r1r1_rel, dot_r0r1r1_rel_coarray