md_3 – ForDot
md_3 Function
Seyed Ali Ghasemi
9 statements
Source File
private pure function md_3(u, v) result(a)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), dimension(:), contiguous :: u
real(kind=rk), intent(in), dimension(:), contiguous :: v
Return Value real(kind=rk)
Called by
Source Code
   pure function md_3(u,v) result(a)
      real(rk), dimension(:), intent(in), contiguous :: u, v
      real(rk) :: a
      integer :: i
      a = 0.0_rk
      do i = 1, size(u)
         a = a + u(i)*v(i)
      end do
   end function md_3
Call graph
dot_r0r1r1_rel_opts calls md_3
dot_opts calls dot_r0r1r1_rel_opts
dot_r0r1r1_rel calls dot_opts
dot_r0r1r1_rel_coarray calls dot_opts
dot_product calls dot_r0r1r1_rel, dot_r0r1r1_rel_coarray