dot – ForDot
dot Interface
20 statements
Source File
public interface dot
Called by
Functions
public pure function ddot(f_n, f_dx, f_incx, f_dy, f_incy) result(f_a)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: f_n
real(kind=rk), intent(in) :: f_dx(f_n)
integer, intent(in) :: f_incx
real(kind=rk), intent(in) :: f_dy(f_n)
integer, intent(in) :: f_incy
Return Value real(kind=rk)
public pure function sdot(f_n, f_dx, f_incx, f_dy, f_incy) result(f_a)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: f_n
real(kind=rk), intent(in) :: f_dx(f_n)
integer, intent(in) :: f_incx
real(kind=rk), intent(in) :: f_dy(f_n)
integer, intent(in) :: f_incy
Return Value real(kind=rk)
public pure function ddot(f_n, f_dx, f_incx, f_dy, f_incy) result(f_a)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: f_n
real(kind=rk), intent(in) :: f_dx(f_n)
integer, intent(in) :: f_incx
real(kind=rk), intent(in) :: f_dy(f_n)
integer, intent(in) :: f_incy
Return Value real(kind=rk)
Call graph
md_2 calls dot
dot_r0r1r1_rel_opts calls md_2
dot_opts calls dot_r0r1r1_rel_opts
dot_r0r1r1_rel calls dot_opts
dot_r0r1r1_rel_default calls dot_opts
dot_product calls dot_r0r1r1_rel, dot_r0r1r1_rel_default