dot_product – ForDot
dot_product Interface
BSD 3-Clause
5 statements
Source File
public interface dot_product
Calls
Called by
Module Procedures
private pure function dot_R0R1R1_rel(u, v, option) result(a)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: u(:)
real(kind=rk), intent(in), contiguous :: v(:)
character(len=*), intent(in), optional :: option
Return Value real(kind=rk)
private pure function dot_R0R1R1_rel_block(u, v, option, nblock) result(a)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: u(:)
real(kind=rk), intent(in), contiguous :: v(:)
character(len=*), intent(in), optional :: option
integer, intent(in) :: nblock
Return Value real(kind=rk)
private impure function dot_R0R1R1_rel_coarray(u, v, option, coarray) result(a)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), contiguous :: u(:)
real(kind=rk), intent(in), contiguous :: v(:)
character(len=*), intent(in), optional :: option
logical, intent(in) :: coarray
Return Value real(kind=rk)
Call graph
dot_product calls dot_r0r1r1_rel, dot_r0r1r1_rel_block, dot_r0r1r1_rel_coarray
dot_r0r1r1_rel calls dot_opts
dot_r0r1r1_rel_block calls compute_block_ranges, reduce
dot_r0r1r1_rel_coarray calls compute_block_ranges
dot_opts calls dot_r0r1r1_rel_opts
dot_r0r1r1_rel_opts calls md_2, md_3, md_4
md_2 calls dot
test_dot1 calls dot_product
test_dot2 calls dot_product