dot_opts – ForDot
dot_opts Interface
BSD 3-Clause
3 statements
Source File
public interface dot_opts
Calls
Called by
Module Procedures
private pure function dot_R0R1R1_rel_opts(u, v, option) result(a)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), dimension(:), contiguous :: u
real(kind=rk), intent(in), dimension(:), contiguous :: v
character(len=*), intent(in) :: option
Return Value real(kind=rk)
Call graph
dot_opts calls dot_r0r1r1_rel_opts
dot_r0r1r1_rel_opts calls md_2, md_3, md_4
md_2 calls dot
dot_r0r1r1_rel calls dot_opts
dot_product calls dot_r0r1r1_rel
test_dot1 calls dot_product
test_dot2 calls dot_product