test_dot2 – ForDot
test_dot2 Program
BSD 3-Clause
27 statements
Source File
Uses
kinds
fordot
forunittest
Calls
Variables
Type Attributes Name Initial
real(kind=rk) :: a
real(kind=rk) :: a_ref
integer :: im
integer :: m
real(kind=rk), allocatable :: u(:)
type(unit_test) :: ut
real(kind=rk), allocatable :: v(:)
Source Code
program test_dot2
   use kinds
   use fordot, only: fdot_product => dot_product ! rename dot_product to fdot_product to avoid overloading
   use forunittest, only: unit_test
   implicit none
   real(rk), allocatable :: u(:), v(:)
   real(rk)              :: a_ref, a
   integer               :: m, im
   type(unit_test)       :: ut
#if defined(USE_COARRAY)
   im = this_image()
#else
   im = 1
#endif
   ! a = u(m).v(n)
   m = 500
   allocate(u(m),v(m))
   call random_number(u)
   call random_number(v)
   u = u*100.0_rk
   v = v*100.0_rk
   a_ref = dot_product(u,v)
   a = fdot_product(u,v, coarray=.true., option='m1')
   if (im==1) call ut%check(a, a_ref, tol=1e-5_rk, msg='test_dot2.1')
   a = fdot_product(u,v, coarray=.true., option='m2')
   if (im==1) call ut%check(a, a_ref, tol=1e-5_rk, msg='test_dot2.2')
   a = fdot_product(u,v, coarray=.true., option='m3')
   if (im==1) call ut%check(a, a_ref, tol=1e-5_rk, msg='test_dot2.3')
   a = fdot_product(u,v, coarray=.true., option='m4')
   if (im==1) call ut%check(a, a_ref, tol=1e-5_rk, msg='test_dot2.4')
end program test_dot2
Call graph
test_dot2 calls check, dot_product
dot_product calls dot_r0r1r1_rel, dot_r0r1r1_rel_block, dot_r0r1r1_rel_coarray
dot_r0r1r1_rel calls dot_opts
dot_r0r1r1_rel_block calls compute_block_ranges, reduce
dot_r0r1r1_rel_coarray calls compute_block_ranges
dot_opts calls dot_r0r1r1_rel_opts
dot_r0r1r1_rel_opts calls md_2, md_3, md_4
md_2 calls dot